# Generated by Django 3.0.4 on 2020-03-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_vid', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
